openapi: 3.0.0
info:
  title: Logging
  version: 1.0.0
paths:
  /log:
    post:
      summary: Log data from batch process
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timeOfInvocation:
                  type: string
                  format: date-time
                  example: "2024-10-16T08:30:00Z"
                recordNumber:
                  type: integer
                  example: 1
                actualPayload:
                  $ref: '#/components/schemas/Payload'
      responses:
        '200':
          description: Log successfully received
        '400':
          description: Bad request
components:
  schemas:
    LogEntry:
      type: object
      properties:
        timeOfInvocation:
          type: string
          format: date-time
          example: "2024-10-16T08:30:00Z"
        recordNumber:
          type: integer
          example: 1
        actualPayload:
          $ref: '#/components/schemas/Payload'
    Payload:
      type: object
      properties:
        id:
          type: integer
          example: 1
        idPol:
          type: integer
          example: 123
        cdescr:
          type: string
          example: "Description of the payload"
        dexpcur:
          type: string
          format: date-time
          example: "2024-10-16T08:30:00Z"
        cplate:
          type: string
          example: "ABC123"
        cbrand:
          type: string
          example: "BrandName"
        cmodel:
          type: string
          example: "ModelName"
        cver:
          type: string
          example: "1.0"
