openapi: 3.0.0
info:
  title: Logging
  version: 1.0.0
servers:
- url: /
paths:
  /log:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_log_post_request'
        required: true
      responses:
        "200":
          description: Log successfully received
        "400":
          description: Bad request
      summary: Log data from batch process
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    LogEntry:
      properties:
        timeOfInvocation:
          example: 2024-10-16T08:30:00Z
          format: date-time
          type: string
        recordNumber:
          example: 1
          type: integer
        actualPayload:
          $ref: '#/components/schemas/Payload'
      type: object
    Payload:
      properties:
        id:
          example: 1
          type: integer
        idPol:
          example: 123
          type: integer
        cdescr:
          example: Description of the payload
          type: string
        dexpcur:
          example: 2024-10-16T08:30:00Z
          format: date-time
          type: string
        cplate:
          example: ABC123
          type: string
        cbrand:
          example: BrandName
          type: string
        cmodel:
          example: ModelName
          type: string
        cver:
          example: "1.0"
          type: string
      type: object
    _log_post_request:
      properties:
        timeOfInvocation:
          example: 2024-10-16T08:30:00Z
          format: date-time
          type: string
        recordNumber:
          example: 1
          type: integer
        actualPayload:
          $ref: '#/components/schemas/Payload'
      type: object
