openapi: 3.0.0
info:
  title: Logging
  version: 1.0.0
servers:
- url: /
paths:
  /log:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_log_post_request'
        required: true
      responses:
        "200":
          description: Log successfully received
        "400":
          description: Bad request
      summary: Log data from batch process
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    LogEntry:
      properties:
        timeOfInvocation:
          example: 2024-10-16T08:30:00Z
          format: date-time
          type: string
        recordNumber:
          example: 1
          type: integer
        actualPayload:
          example: Payload string content
          type: string
      type: object
    _log_post_request:
      properties:
        timeOfInvocation:
          example: 2024-10-16T08:30:00Z
          format: date-time
          type: string
        recordNumber:
          example: 1
          type: integer
        actualPayload:
          example: Payload string content
          type: string
      type: object
